selection.aov2 <- c("Lebensqualallg",
                    "Sex",
                    "Altergruppe",
                    "Quartier",
                    "Zuzug", 
                    "Erwerb",
                    "v_294",
                    "v_79",
                    "v_355",
                    "v_357",
                    "v_302",
                    "v_311",
                    "v_39",
                    "v_323",
                    "v_325",
                    "v_106",
                    "v_212",
                    "v_366",
                    "v_367",
                    "v_293",
                    "v_256",
                    "v_229")

df.aov.selected <- df.aov.selected %>% rename(v_362_Attraktivitaet_Gemeinschaftsbueros = v_364,
                                              v_79_Wohnsituation_Umgebung_des_Hauses = v_79,
                                              v_357_Moeglichkeit_Vorschlagen_Projekte = v_357,
                                              v_359_Wuenscht_Infrastruktur_Freizeiteinrichtungen = v_359,
                                              v_86_Unzufrieden_weil_kein_Gemeinschatfsgefuehl = v_86,
                                              v_56_Zufrieden_mit_Kulturangebot = v_56,
                                              v_305_Kultur_wichtig_Vereinsleben = v_305,
                                              v_306_Kultur_wichtig_Esskultur = v_306,
                                              v_41_Fuehlt_sicher_Velo = v_41,
                                              v_42_Fuehlt_sicher_zu_Fuss = v_42,
                                              v_50_Erreichbarkeit_Wohnung_mit_OV = v_50,
                                              v_51_Erreichbarkeit_Wohnung_mit_OV = v_51,
                                              v_187_Dauer_Gruenphase_Fussgaenger = v_187,
                                              v_279_Anzahl_Veloparkplaetze_Allg = v_279,
                                              v_280_Anzahl_Veloparkplaetze_Bhf = v_280,
                                              v_324_Anbindung_Velo_Bahn = v_324,
                                              v_325_Anbindung_Velo_Bus = v_325,
                                              v_316_Moeglichkeit_bekannt_stadt_Ebene = v_316,
                                              v_106_Moeglichkeit_Einbringen_stadt_Ebene = v_106,
                                              v_212_Moeglichkeiten_bekannt_stadt_Projekte = v_212,
                                              v_366_Moeglichkeit_Einbringen_stadt_Projekte = v_366,
                                              V_248_Wuenscht_mehr_Baeume = v_248)